### ISSUE TITLE
Questions about paper description and code implementation

### ISSUE THREAD

**Issue by Gwencong** [maybeLx/MVSFormerPlusPlus#4]
Thank you for your excellent work. After reading the paper and code, I have two more questions about the SVA section:

Firstly, the SVA module in Figure 2 of the paper contains 4 self attention and 5 cross attention, but in the code implementation, there are only 2 self attention and 3 cross attention.

Secondly, the SVA described in Figure 3 of the paper is also different from the code implementation. What troubles me the most is that $F_0^{l+1}$ and $F_i^{l+1}$  in Figure 3 serves as both input and output of SVA, and the inference order of self attention, cross attention, and Adaptive Layer Scaling $S^l$ is different from the code implementation.

**Comment by maybeLx** [comment]
I apologize for the misunderstanding . Due to the age of the code, it was initially trained based on the code structure.  We  implemented SVA module using `CrossVITDecoder` and `FMT`. Then our design approach, as illustrated in Figure 3,  utilizing features $F^{l}$ from the l-th layer and features $F^{l+1}$ from the subsequent layer of DINOv2 within the attention mechanism to generate new features $F^{l+1}$.

**Comment by maybeLx** [comment]
We use norm layer inside the attention block, and we only normalized the query `q`  .

**Comment by Gwencong** [comment]
Thank you for your reply. I have tried the SVA module in my own code and the improvement is quite significant. The overall reconstruction error on the DTU test set has been reduced from 0.317 to 0.305 with a certain Gipuma parameter. This is an outstanding achievement.
